services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - 6969:80
    volumes:
      - ./html:/usr/local/apache2/htdocs
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: learndocker
    volumes:
      - kms23-learn-docker-dbdata:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  kms23-learn-docker-dbdata: